fixed icinga director kickstart

diff --git a/content/opt/supervisor/icinga2_supervisor b/content/opt/supervisor/icinga2_supervisor
--- a/content/opt/supervisor/icinga2_supervisor
+++ b/content/opt/supervisor/icinga2_supervisor
@@ -3,21 +3,38 @@
 . /opt/helpers
 
 echo "=> Starting Icinga Daemon"
-icinga2 daemon &
-ICINGA2_PID=$!
-echo "==> PID: $ICINGA2_PID"
+icinga2 daemon -d
 
 # Kickstart is only possible after icinga2 start -> not in setup script
 if    evaluate_boolean "${ICINGA2_FEATURE_DIRECTOR}" \
    && evaluate_boolean "${ICINGA2_FEATURE_DIRECTOR_KICKSTART}"; then
-    echo "=> Running Icinga Director Kickstarter"
+    echo "=> Running Icinga Director Kickstart"
     # todo check if icinga is up another way
     sleep 10s
-	icingacli director kickstart run
-    echo "=> Running Icinga Director Kickstarter...done"
+    echo "=> icingacli director migration run"
+    icingacli director migration run
+    echo "=> icingacli director kickstart required --verbose"
+    icingacli director kickstart required --verbose
+    echo "=> icingacli director kickstart run"
+	icingacli director kickstart run &
+    KICKSTARTERPID=$!
+    sleep 10
+    kill $KICKSTARTERPID
+    echo "=> icingacli director config deploy"
+    icingacli director config deploy
 fi
 
 # Allow any signal which would kill a process to stop server
-trap "kill $ICINGA2_PID" HUP INT QUIT ABRT ALRM TERM TSTP
+trap "killall icinga2" HUP INT QUIT ABRT ALRM TERM TSTP
 
-wait $ICINGA2_PID
+i=0
+while [ $i -lt 5 ] ; do
+    sleep 5
+    if pgrep -x "icinga2" > /dev/null
+    then
+        i=0
+    else
+        i=$[$i+1]
+        echo "=> No icinga process found ($i)"
+    fi
+done
